SELECT
    YEAR(DIFFERENTIATION_DATE) AS YEAR,
    (max_size - SIZE_OF_COLONY) AS YEAR_DEV,
    ID
FROM (
    SELECT
        ID,
        SIZE_OF_COLONY,
        DIFFERENTIATION_DATE,
        MAX(SIZE_OF_COLONY) OVER (PARTITION BY YEAR(DIFFERENTIATION_DATE)) AS max_size
    FROM ECOLI_DATA
) t
ORDER BY
    YEAR ASC,
    YEAR_DEV ASC